# Generated by Django 4.2.7 on 2026-09-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gold', 'طلا'), ('silver', 'نقره'), ('currency', 'ارز'), ('gemstone', 'سنگ قیمتی')], max_length=15, verbose_name='نوع')),
                ('label', models.CharField(max_length=100, verbose_name='عنوان')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار/فی')),
                ('currency', models.CharField(default='افغانی', max_length=20, verbose_name='واحد پول')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
            ],
            options={
                'verbose_name': 'نرخ روز',
                'verbose_name_plural': 'نرخ\u200cهای روز',
            },
        ),
    ]
