# Generated by Django 4.2.7 on 2026-09-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='وزن (گرم)')),
                ('material', models.CharField(choices=[('gold', 'طلا'), ('silver', 'نقره'), ('jewelry', 'جواهر')], max_length=10, verbose_name='جنس کالا')),
                ('carat', models.CharField(blank=True, max_length=50, null=True, verbose_name='عیار')),
                ('stone_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع سنگ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد/موجودی')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('is_returned', models.BooleanField(default=False, verbose_name='مرجوعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.country', verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
