# Generated by Django 4.2.7 on 2026-09-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_updated_by'),
    ]

    operations = [
    ]
