# Generated by Django 4.2.7 on 2026-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20260917_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل موجودی (هشدار)'),
        ),
    ]
