# Generated by Django 4.2.7 on 2026-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deduct_from_melt',
            field=models.BooleanField(default=False, verbose_name='کسر از موجودی ذوب'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='قیمت خرید'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_hand_destination',
            field=models.CharField(blank=True, choices=[('inventory', 'انبار فروش'), ('melt', 'ذوب')], max_length=20, null=True, verbose_name='مقصد خرید دست دوم'),
        ),
    ]
