# Generated by Django 4.2.7 on 2026-09-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255)),
                ('code_snapshot', models.CharField(blank=True, max_length=50)),
                ('material_snapshot', models.CharField(blank=True, max_length=10)),
                ('carat_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('stone_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
