# Generated by Django 4.2.7 on 2026-09-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='قیمت خرید ثبتی'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مصرف یا برداشت')),
                ('category', models.CharField(choices=[('rent', 'کرایه دکان/مغازه'), ('salary', 'معاش و حقوق کارمندان'), ('utility', 'مصارف جاری و انرژی'), ('withdrawal', 'برداشت شخصی'), ('other', 'سایر مصارف')], default='other', max_length=20, verbose_name='دسته\u200cبندی')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ (افغانی)')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='دریافت\u200cکننده یا مسئول برداشت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'مصرف / برداشت',
                'verbose_name_plural': 'مصارف و برداشت\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
